rules:
  one-var: [error, never]
  no-new-object: error
  quote-props: [error, as-needed]
  no-useless-computed-key: error
  object-curly-newline: [error, { multiline: true }]
  object-property-newline: [error, { allowAllPropertiesOnSameLine: true }]
  key-spacing: [error, { beforeColon: false, afterColon: true, mode: strict }]
  comma-spacing: [error, { before: false, after: true }]
  comma-dangle: [error, never]
  indent: [error, tab]
  no-trailing-spaces: error
  no-array-constructor: error
  array-bracket-newline: [error, { multiline: true }]
  array-bracket-spacing: [error, never]
  array-element-newline: [error, consistent]
  brace-style: [error, 1tbs, { allowSingleLine: false }]
  eol-last: [error, always]
  id-length: [error, exceptions: [e]]
  camelcase: error
  new-cap: error
  no-underscore-dangle: error
